bundler_args: --without development
before_install: gem install bundler
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - jruby-19mode
#  - 1.9.3
#  - 2.3.1
  - jruby-head
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
sudo: false
