bundler_args: --without development
before_install:
  - gem install bundler --version 1.17.3
install:
  - bundle _1.17.3_ install --jobs=3 --retry=3
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - jruby-9.2.7.0
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
sudo: false
