name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
          - 3.2
          - head
          - debug
          - truffleruby
          - truffleruby-head
          - jruby
          # - jruby-head TODO: Add back jruby-head once we figure out why there's a bundler mismatch
    env:
      JRUBY_OPTS: --debug
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
  frozen-string-compat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Run tests
      env:
        RUBYOPT: "--enable-frozen-string-literal"
      run: bundle exec rake
  coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: './coverage/lcov/omniauth.lcov'
